(function () {
  const PATTERNS = {
    all: [1, 1, 1, 1, 1, 1, 1, 1, 1],
    dot: [0, 0, 0, 0, 1, 0, 0, 0, 0],
    line: [0, 1, 0, 0, 1, 0, 0, 1, 0],
    cross: [0, 1, 0, 1, 1, 1, 0, 1, 0],
    l: [1, 1, 0, 1, 0, 0, 0, 0, 0],
    t: [0, 1, 0, 1, 1, 1, 0, 0, 0],
    s: [0, 1, 1, 1, 1, 0, 0, 0, 0],
    diag: [1, 0, 0, 0, 1, 0, 0, 0, 1],
    corners: [1, 0, 1, 0, 1, 0, 1, 0, 1]
  };

  const OLL_BASE = [
    { id: "OLL_01", type: "OLL", name: "OLL 1", alg: "R U2' R2 F R F' U2' (R' F R F')", youtubeUrl: "https://www.youtube-nocookie.com/embed/Krt5t5X9gTo", setupMoves: "F R' F' R U2 F R' F' R2 U2 R'" },
    { id: "OLL_02", type: "OLL", name: "OLL 2", alg: "F (R U R' U') F' f (R U R' U') f'", youtubeUrl: "https://www.youtube-nocookie.com/embed/EyCwdkn03sM", setupMoves: "f U R U' R' f' F U R U' R' F'" },
    { id: "OLL_03", type: "OLL", name: "OLL 3", alg: "f (R U R' U') f' U' F (R U R' U') F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/KdgjbaG0YmI", setupMoves: "F U R U' R' F' U f U R U' R' f'" },
    { id: "OLL_04", type: "OLL", name: "OLL 4", alg: "f (R U R' U' f') U F (R U R' U') F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/JlGs-0-RxJk", setupMoves: "F U R U' R' F' U' f U R U' R' f'" },
    { id: "OLL_05", type: "OLL", name: "OLL 5", alg: "r' U2 R U R' U r", youtubeUrl: "https://www.youtube-nocookie.com/embed/zDAhS61IFlw", setupMoves: "r' U' R U' R' U2 r" },
    { id: "OLL_06", type: "OLL", name: "OLL 6", alg: "r U2 R' U' R U' r'", youtubeUrl: "https://www.youtube-nocookie.com/embed/xtuAlp8AAj8", setupMoves: "r U R' U R U2 r'" },
    { id: "OLL_07", type: "OLL", name: "OLL 7", alg: "r U R' U R U2 r'", youtubeUrl: "https://www.youtube-nocookie.com/embed/Ls-uPCQbjqg", setupMoves: "r U2 R' U' R U' r'" },
    { id: "OLL_08", type: "OLL", name: "OLL 8", alg: "r' U' R U' R' U2 r", youtubeUrl: "https://www.youtube-nocookie.com/embed/Vptj1rtxcxA", setupMoves: "r' U2 R U R' U r" },
    { id: "OLL_09", type: "OLL", name: "OLL 9", alg: "(R U R' U') R' F R2 U R' U' F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/1tkJ78gxtfU", setupMoves: "F U R U' R2 F' R U R U' R'" },
    { id: "OLL_10", type: "OLL", name: "OLL 10", alg: "(R U R' U) (R' F R F') R U2 R'", youtubeUrl: "https://www.youtube-nocookie.com/embed/RPjJagkkvwM", setupMoves: "R U2 R' F R' F' R U' R U' R'" },
    { id: "OLL_11", type: "OLL", name: "OLL 11", alg: "r' R2 U R' U R U2 R' U M'", youtubeUrl: "https://www.youtube-nocookie.com/embed/YsNvf0oUw9U", setupMoves: "M U' R U2 R' U' R U' R2 r" },
    { id: "OLL_12", type: "OLL", name: "OLL 12", alg: "r R2' U' R U' R' U2 R U' M", youtubeUrl: "https://www.youtube-nocookie.com/embed/E5WsvlCzOrM", setupMoves: "M' U R' U2 R U R' U R2 r'" },
    { id: "OLL_13", type: "OLL", name: "OLL 13", alg: "F U (R U2 R') (U' R U R') F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/Xz96dRD2DaI", setupMoves: "F R U' R' U R U2 R' U' F'" },
    { id: "OLL_14", type: "OLL", name: "OLL 14", alg: "R' F R U R' F' R F U' F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/xEoC4d91yAc", setupMoves: "F U F' R' F R U' R' F' R" },
    { id: "OLL_15", type: "OLL", name: "OLL 15", alg: "(r' U' r) (R' U' R U) (r' U r)", youtubeUrl: "https://www.youtube-nocookie.com/embed/VeG5V1a6pHA", setupMoves: "r' U' r U' R' U R r' U r" },
    { id: "OLL_16", type: "OLL", name: "OLL 16", alg: "(r U r') (R U R' U') (r U' r')", youtubeUrl: "https://www.youtube-nocookie.com/embed/Gar0BFyHWXs", setupMoves: "r U r' U R U' R' r U' r'" },
    { id: "OLL_17", type: "OLL", name: "OLL 17", alg: "(R U R' U) (R' F R F') U2 (R' F R F')", youtubeUrl: "https://www.youtube-nocookie.com/embed/4QtUb6tleZE", setupMoves: "F R' F' R U2 F R' F' R U' R U' R'" },
    { id: "OLL_18", type: "OLL", name: "OLL 18", alg: "R U2 R2 F R F' U2 M' U R U' r'", youtubeUrl: "https://www.youtube-nocookie.com/embed/2jrDoX0AQCc", setupMoves: "r U' R' U M U2 F R' F' R2 U2 R'" },
    { id: "OLL_19", type: "OLL", name: "OLL 19", alg: "r' R U R U R' U' r R2 F R F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/OUTQriBA888", setupMoves: "F R' F' R2 r' U R U' R' U' R' U' R' r" },
    { id: "OLL_20", type: "OLL", name: "OLL 20", alg: "r' R U R U R' U' M2 U R U' r'", youtubeUrl: "https://www.youtube-nocookie.com/embed/Mlfmfv8KFOU", setupMoves: "r U' R' U' M2 U R U' R' U' R' U' R' r" },
    { id: "OLL_21", type: "OLL", name: "OLL 21", alg: "(R U R' U) (R U' R' U) R U2 R'", youtubeUrl: "https://www.youtube-nocookie.com/embed/LkLCxmV63Sc", setupMoves: "R U2 R' U' R U R' U' R U' R'" },
    { id: "OLL_22", type: "OLL", name: "OLL 22", alg: "R U2 (R2 U') (R2 U') R2 U2 R", youtubeUrl: "https://www.youtube-nocookie.com/embed/Z6SYc0MyBnk", setupMoves: "R' U2 R2 U R2 U R2 U2 R'" },
    { id: "OLL_23", type: "OLL", name: "OLL 23", alg: "R2 D R' U2 R D' R' U2 R'", youtubeUrl: "https://www.youtube-nocookie.com/embed/YvgWA5n7-y0", setupMoves: "R U2 R D R' U2 R D' R2" },
    { id: "OLL_24", type: "OLL", name: "OLL 24", alg: "r U R' U' r' F R F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/5pmKYnWCNiI", setupMoves: "F R' F' r U R' U' r'" },
    { id: "OLL_25", type: "OLL", name: "OLL 25", alg: "F' r U R' U' r' F R", youtubeUrl: "https://www.youtube-nocookie.com/embed/w2pqzFn0KqU", setupMoves: "R' F' r U R' U' r' F" },
    { id: "OLL_26", type: "OLL", name: "OLL 26", alg: "R U2 R' U' R U' R'", youtubeUrl: "https://www.youtube-nocookie.com/embed/W4E8fo6-D84", setupMoves: "R U R' U R U2 R'" },
    { id: "OLL_27", type: "OLL", name: "OLL 27", alg: "R U R' U R U2 R'", youtubeUrl: "https://www.youtube-nocookie.com/embed/83GLN0XmCNA", setupMoves: "R U2 R' U' R U' R'" },
    { id: "OLL_28", type: "OLL", name: "OLL 28", alg: "r U R' U' M U R U' R'", youtubeUrl: "https://www.youtube-nocookie.com/embed/blOdiGsmlQQ", setupMoves: "R U R' U' M' U R U' r'" },
    { id: "OLL_29", type: "OLL", name: "OLL 29", alg: "(R U R' U') (R U' R') (F' U' F) (R U R')", youtubeUrl: "https://www.youtube-nocookie.com/embed/xaSQb6RdIrY", setupMoves: "R U' R' F' U F R U R' U R U' R'" },
    { id: "OLL_30", type: "OLL", name: "OLL 30", alg: "r' D' r U' r' D r2 U' r' U r U r'", youtubeUrl: "https://www.youtube-nocookie.com/embed/HSDYQ3F9_GQ", setupMoves: "r U' r' U' r U r2 D' r' D r" },
    { id: "OLL_31", type: "OLL", name: "OLL 31", alg: "R' U' F U R U' R' F' R", youtubeUrl: "https://www.youtube-nocookie.com/embed/d5krfXeAvZ8", setupMoves: "R' F R U R' U' F' U R" },
    { id: "OLL_32", type: "OLL", name: "OLL 32", alg: "S R U R' U' R' F R f'", youtubeUrl: "https://www.youtube-nocookie.com/embed/fK4goEB_xPg", setupMoves: "f R' F' R U R U' R' S'" },
    { id: "OLL_33", type: "OLL", name: "OLL 33", alg: "(R U R' U') (R' F R F')", youtubeUrl: "https://www.youtube-nocookie.com/embed/yw6EhRi2Ylo", setupMoves: "F R' F' R U R U' R'" },
    { id: "OLL_34", type: "OLL", name: "OLL 34", alg: "R U R2 U' R' F R U R U' F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/tOB1D8nmMIs", setupMoves: "F U R' U' R' F' R U R2 U' R'" },
    { id: "OLL_35", type: "OLL", name: "OLL 35", alg: "R U2' R2' F R F' R U2' R'", youtubeUrl: "https://www.youtube-nocookie.com/embed/bG14LWhXWCk", setupMoves: "R U2 R' F R' F' R2 U2 R'" },
    { id: "OLL_36", type: "OLL", name: "OLL 36", alg: "L' U' L U' L' U L U L F' L' F", youtubeUrl: "https://www.youtube-nocookie.com/embed/6E5tMt6BGog", setupMoves: "F' L F L' U' L' U' L U L' U L U L" },
    { id: "OLL_37", type: "OLL", name: "OLL 37", alg: "F R U' R' U' R U R' F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/1uNKnyKiFOo", setupMoves: "F R U' R' U' R U R' F'" },
    { id: "OLL_38", type: "OLL", name: "OLL 38", alg: "R U R' U R U' R' U' (R' F R F')", youtubeUrl: "https://www.youtube-nocookie.com/embed/-OHDLxFILFU", setupMoves: "F R' F' R U U R U R' U R U' R'" },
    { id: "OLL_39", type: "OLL", name: "OLL 39", alg: "L F' L' U' L U F U' L'", youtubeUrl: "https://www.youtube-nocookie.com/embed/frAvYb9HoYo", setupMoves: "L U F' U' L' U L F L'" },
    { id: "OLL_40", type: "OLL", name: "OLL 40", alg: "R' F R U R' U' F' U R", youtubeUrl: "https://www.youtube-nocookie.com/embed/fYZxskw2EgI", setupMoves: "R' U' F U R U' R' F' R" },
    { id: "OLL_41", type: "OLL", name: "OLL 41", alg: "R U R' U R U2 R' F (R U R' U') F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/AmxQNjhBzfk", setupMoves: "F U R U' R' F' U2 R U' R' U' R" },
    { id: "OLL_42", type: "OLL", name: "OLL 42", alg: "R' U' R U' R' U2 R F (R U R' U') F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/uL5R2Hx2fV8", setupMoves: "F U R U' R' F' U2 R' U R U R" },
    { id: "OLL_43", type: "OLL", name: "OLL 43", alg: "R' U' F' U F R", youtubeUrl: "https://www.youtube-nocookie.com/embed/joYVuCv8p-E", setupMoves: "R' F' U' F U R" },
    { id: "OLL_44", type: "OLL", name: "OLL 44", alg: "F U R U' R' F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/CeqGe0Q1wMg", setupMoves: "F R U R' U' F'" },
    { id: "OLL_45", type: "OLL", name: "OLL 45", alg: "F (R U R' U') F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/3HJQsUqEqyM", setupMoves: "F U R U' R' F'" },
    { id: "OLL_46", type: "OLL", name: "OLL 46", alg: "R' U' R' F R F' U R", youtubeUrl: "https://www.youtube-nocookie.com/embed/AQynWJ4dAjk", setupMoves: "R' U' F R' F' R U R" },
    { id: "OLL_47", type: "OLL", name: "OLL 47", alg: "R' U' (R' F R F') (R' F R F') U R", youtubeUrl: "https://www.youtube-nocookie.com/embed/9Ui1n0UjaCU", setupMoves: "R' U' F R' F' R F R' F' R U R" },
    { id: "OLL_48", type: "OLL", name: "OLL 48", alg: "F (R U R' U') (R U R' U') F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/-yAt0RgMmsY", setupMoves: "F U R U' R' U R U' R' F'" },
    { id: "OLL_49", type: "OLL", name: "OLL 49", alg: "r U' r2 U r2 U r2 U' r", youtubeUrl: "https://www.youtube-nocookie.com/embed/dQrWHwyT8bo", setupMoves: "r' U r2 U' r2 U' r2 U r'" },
    { id: "OLL_50", type: "OLL", name: "OLL 50", alg: "r' U r2 U' r2 U' r2 U r'", youtubeUrl: "https://www.youtube-nocookie.com/embed/0jwU3QUs93g", setupMoves: "r U' r2 U r2 U r2 U' r" },
    { id: "OLL_51", type: "OLL", name: "OLL 51", alg: "F (U R U' R') (U R U' R') F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/6j4D0FHgSOY", setupMoves: "F R U R' U' R U R' U' F'" },
    { id: "OLL_52", type: "OLL", name: "OLL 52", alg: "R' F' U' F U' R U R' U R", youtubeUrl: "https://www.youtube-nocookie.com/embed/ZuRxOkExG8o", setupMoves: "R' U' R U' R' U F' U F R" },
    { id: "OLL_53", type: "OLL", name: "OLL 53", alg: "r' U' R U' R' U R U' R' U2 r", youtubeUrl: "https://www.youtube-nocookie.com/embed/FV3aJg0kmIw", setupMoves: "r' U2 R U R' U' R U R' U r" },
    { id: "OLL_54", type: "OLL", name: "OLL 54", alg: "r U R' U R U' R' U R U2 r'", youtubeUrl: "https://www.youtube-nocookie.com/embed/gydKjGqInfg", setupMoves: "r U2 R' U' R U R' U' R U' r'" },
    { id: "OLL_55", type: "OLL", name: "OLL 55", alg: "R U2 R2 U' R U' R' U2 F R F'", youtubeUrl: "https://www.youtube-nocookie.com/embed/QDehoJhTOtY", setupMoves: "F R' F' U2 R U R' U R2 U2 R'" },
    { id: "OLL_56", type: "OLL", name: "OLL 56", alg: "(r U r') (U R U' R') (U R U' R') (r U' r')", youtubeUrl: "https://www.youtube-nocookie.com/embed/KZkE5GBzS9k", setupMoves: "r U r' R U R' U' R U R' U' r U' r'" },
    { id: "OLL_57", type: "OLL", name: "OLL 57", alg: "(R U R' U') M' U R U' r'", youtubeUrl: "https://www.youtube-nocookie.com/embed/qHvJd0pk41Q", setupMoves: "r U R' U' M U R U' R'" }
];


  const OLL_PATTERNS = {
    OLL_01: [0, 0, 0, 0, 1, 0, 0, 0, 0],
    OLL_02: [0, 0, 0, 0, 1, 0, 0, 0, 0],
    OLL_03: [0, 0, 0, 0, 1, 0, 0, 0, 1],
    OLL_04: [0, 0, 1, 0, 1, 0, 0, 0, 0],
    OLL_05: [0, 0, 0, 0, 1, 1, 0, 1, 1],
    OLL_06: [0, 1, 1, 0, 1, 1, 0, 0, 0],
    OLL_07: [0, 1, 0, 1, 1, 0, 1, 0, 0],
    OLL_08: [1, 0, 0, 1, 1, 0, 0, 1, 0],
    OLL_09: [0, 1, 0, 1, 1, 0, 0, 0, 1],
    OLL_10: [0, 0, 1, 1, 1, 0, 0, 1, 0],
    OLL_11: [0, 0, 0, 0, 1, 1, 1, 1, 0],
    OLL_12: [1, 1, 0, 0, 1, 1, 0, 0, 0],
    OLL_13: [0, 0, 0, 1, 1, 1, 1, 0, 0],
    OLL_14: [0, 0, 0, 1, 1, 1, 0, 0, 1],
    OLL_15: [0, 0, 0, 1, 1, 1, 0, 0, 1],
    OLL_16: [0, 0, 1, 1, 1, 1, 0, 0, 0],
    OLL_17: [1, 0, 0, 0, 1, 0, 0, 0, 1],
    OLL_18: [1, 0, 1, 0, 1, 0, 0, 0, 0],
    OLL_19: [1, 0, 1, 0, 1, 0, 0, 0, 0],
    OLL_20: [1, 0, 1, 0, 1, 0, 1, 0, 1],
    OLL_21: [0, 1, 0, 1, 1, 1, 0, 1, 0],
    OLL_22: [0, 1, 0, 1, 1, 1, 0, 1, 0],
    OLL_23: [1, 1, 1, 1, 1, 1, 0, 1, 0],
    OLL_24: [0, 1, 1, 1, 1, 1, 0, 1, 1],
    OLL_25: [1, 1, 0, 1, 1, 1, 0, 1, 1],
    OLL_26: [0, 1, 1, 1, 1, 1, 0, 1, 0],
    OLL_27: [0, 1, 0, 1, 1, 1, 1, 1, 0],
    OLL_28: [1, 1, 1, 1, 1, 0, 1, 0, 1],
    OLL_29: [1, 0, 1, 1, 1, 0, 0, 1, 0],
    OLL_30: [1, 1, 0, 0, 1, 1, 1, 0, 0],
    OLL_31: [0, 1, 1, 0, 1, 1, 0, 0, 1],
    OLL_32: [0, 0, 1, 0, 1, 1, 0, 1, 1],
    OLL_33: [0, 0, 1, 1, 1, 1, 0, 0, 1],
    OLL_34: [0, 0, 0, 1, 1, 1, 1, 0, 1],
    OLL_35: [1, 0, 0, 0, 1, 1, 0, 1, 1],
    OLL_36: [1, 0, 0, 1, 1, 0, 0, 1, 1],
    OLL_37: [1, 1, 0, 1, 1, 0, 0, 0, 1],
    OLL_38: [0, 1, 1, 1, 1, 0, 1, 0, 0],
    OLL_39: [0, 0, 1, 1, 1, 1, 1, 0, 0],
    OLL_40: [1, 0, 0, 1, 1, 1, 0, 0, 1],
    OLL_41: [0, 1, 0, 1, 1, 0, 1, 0, 1],
    OLL_42: [1, 0, 1, 1, 1, 0, 0, 1, 0],
    OLL_43: [1, 0, 0, 1, 1, 0, 1, 1, 0],
    OLL_44: [0, 0, 1, 0, 1, 1, 0, 1, 1],
    OLL_45: [0, 0, 1, 1, 1, 1, 0, 0, 1],
    OLL_46: [1, 1, 0, 0, 1, 0, 1, 1, 0],
    OLL_47: [0, 1, 0, 0, 1, 1, 0, 0, 0],
    OLL_48: [0, 1, 0, 1, 1, 0, 0, 0, 0],
    OLL_49: [0, 1, 0, 0, 1, 1, 0, 0, 0],
    OLL_50: [0, 0, 0, 0, 1, 1, 0, 1, 0],
    OLL_51: [0, 0, 0, 1, 1, 1, 0, 0, 0],
    OLL_52: [0, 1, 0, 0, 1, 0, 0, 1, 0],
    OLL_53: [0, 0, 0, 0, 1, 1, 0, 1, 0],
    OLL_54: [0, 1, 0, 0, 1, 1, 0, 0, 0],
    OLL_55: [0, 1, 0, 0, 1, 0, 0, 1, 0],
    OLL_56: [0, 0, 0, 1, 1, 1, 0, 0, 0],
    OLL_57: [1, 0, 1, 1, 1, 1, 1, 0, 1]
  };

  const PLL_BASE = [
    { id: "PLL_Ub", type: "PLL", name: "Ub Perm", alg: "R' U R' U' R3 U' R' U R U R2", youtubeUrl: "https://www.youtube-nocookie.com/embed/mssHbM4JYOc", setupMoves: "R2 U' R' U' R U R U R U' R" },
    { id: "PLL_Ua", type: "PLL", name: "Ua Perm", alg: "R U R' U R' U' R2 U' R' U R' U R", youtubeUrl: "https://www.youtube-nocookie.com/embed/WNkmbgnvQPU", setupMoves: "R' U' R U' R U R2 U R U' R U' R'" },
    { id: "PLL_Z", type: "PLL", name: "Z Perm", alg: "(M2 U') (M2 U') M' U2 M2 U2 M'", youtubeUrl: "https://www.youtube-nocookie.com/embed/I0haU9Z2MeA", setupMoves: "M U2 M2 U2 M U M2 U M2" },
    { id: "PLL_H", type: "PLL", name: "H Perm", alg: "(M2 U' M2) U2 (M2 U' M2)", youtubeUrl: "https://www.youtube-nocookie.com/embed/pmA8ToRfOXQ", setupMoves: "M2 U M2 U2 M2 U M2" },
    { id: "PLL_Aa", type: "PLL", name: "Aa Perm", alg: "x R' U R' D2 R U' R' D2 R2 x'", youtubeUrl: "https://www.youtube-nocookie.com/embed/ibDaGbBp1wY", setupMoves: "x R2 D2 R U R' D2 R U' R x'" },
    { id: "PLL_Ab", type: "PLL", name: "Ab Perm", alg: "x R2 D2 R U R' D2 R U' R x'", youtubeUrl: "https://www.youtube-nocookie.com/embed/Nd0NvF4PF-g", setupMoves: "x R' U R' D2 R U' R' D2 R2 x'" },
    { id: "PLL_E", type: "PLL", name: "E Perm", alg: "x' (R U' R' D) (R U R' D') (R U R' D) (R U' R' D') x", youtubeUrl: "https://www.youtube-nocookie.com/embed/ifo0uz8s4cI", setupMoves: "x' D R U R' D' R U' R' D R U' R' D' R U R' x" },
    { id: "PLL_Ga", type: "PLL", name: "Ga Perm", alg: "R2 U R' U R' U' R U' R2 (D U') R' U R D'", youtubeUrl: "https://www.youtube-nocookie.com/embed/wd4gd8B7QSA", setupMoves: "D R' U' R U D' R2 U R' U R U' R U' R2" },
    { id: "PLL_Gb", type: "PLL", name: "Gb Perm", alg: "D R' U' R (U D') R2 U R' U R U' R U' R2", youtubeUrl: "https://www.youtube-nocookie.com/embed/8fJRWcKSMUk", setupMoves: "R2 U R' U R' U' R U' R2 D U' R' U R D'" },
    { id: "PLL_Gc", type: "PLL", name: "Gc Perm", alg: "R2 U' R U' R U R' U R2 (D' U) R U' R' D", youtubeUrl: "https://www.youtube-nocookie.com/embed/L8C6nY-Qy3E", setupMoves: "D' R U R' U' D R2 U' R U' R' U R' U R2" },
    { id: "PLL_Gd", type: "PLL", name: "Gd Perm", alg: "D' R U R' (U' D) R2 U' R U' R' U R' U R2", youtubeUrl: "https://www.youtube-nocookie.com/embed/ESv6a7Cid6c", setupMoves: "R2 U' R U' R U R' U R2 D' U R U' R' D" },
    { id: "PLL_Ra", type: "PLL", name: "Ra Perm", alg: "(R U' R' U') (R U R D) (R' U' R D') R' U2 R'", youtubeUrl: "https://www.youtube-nocookie.com/embed/IGHfp6CgfaA", setupMoves: "R U2 R D R' U R D' R' U' R' U R U R'" },
    { id: "PLL_Rb", type: "PLL", name: "Rb Perm", alg: "(R' U2) (R U2') R' F (R U R' U') R' F' R2", youtubeUrl: "https://www.youtube-nocookie.com/embed/FwXr8Cawxfg", setupMoves: "R2 F R U R U' R' F' R U2 R' U2 R" },
    { id: "PLL_Ja", type: "PLL", name: "Ja Perm", alg: "(R' U L') U2 (R U' R') U2 R L", youtubeUrl: "https://www.youtube-nocookie.com/embed/nh9th-AYF_8", setupMoves: "L' R' U2 R U R' U2 L U' R" },
    { id: "PLL_Jb", type: "PLL", name: "Jb Perm", alg: "(R U R' F') (R U R' U') R' F R2 U' R'", youtubeUrl: "https://www.youtube-nocookie.com/embed/QXIIxGzMftw", setupMoves: "R U R2 F' R U R U' R' F R U' R'" },
    { id: "PLL_T", type: "PLL", name: "T Perm", alg: "(R U R' U') R' F R2 U' R' U' (R U R' F')", youtubeUrl: "https://www.youtube-nocookie.com/embed/PX1R7VW9YTs", setupMoves: "F R U' R' U R U R2 F' R U R U' R'" },
    { id: "PLL_F", type: "PLL", name: "F Perm", alg: "R' U' F' (R U R' U') R' F (R2 U' R' U') (R U R') U R", youtubeUrl: "https://www.youtube-nocookie.com/embed/KLL-Qt9Lm90", setupMoves: "R' U' R U' R' U R U R2 F' R U R U' R' F U R" },
    { id: "PLL_V", type: "PLL", name: "V Perm", alg: "(R' U R' U') y R' F' R2 U' R' U R' F R F", youtubeUrl: "https://www.youtube-nocookie.com/embed/Ud9ZDcS2yRk", setupMoves: "F' R' F' R U' R U R2 F R y' U R U' R" },
    { id: "PLL_Y", type: "PLL", name: "Y Perm", alg: "F R U' R' U' R U R' F' (R U R' U') (R' F R F')", youtubeUrl: "https://www.youtube-nocookie.com/embed/gC3LvhSAXSA", setupMoves: "F R' F' R U R U' R' F R U' R' U R U R' F'" },
    { id: "PLL_Na", type: "PLL", name: "Na Perm", alg: "F' (R U R' U') R' F R2 F (U' R' U') R U F' R'", youtubeUrl: "https://www.youtube-nocookie.com/embed/iNfx--vOxd0", setupMoves: "R F U' R' U R U F' R2 F' R U R U' R' F" },
    { id: "PLL_Nb", type: "PLL", name: "Nb Perm", alg: "r' D' F (r U' r)' F' D r2 U r' U' (r' F r F')", youtubeUrl: "https://www.youtube-nocookie.com/embed/P5yMlQQ3nsM", setupMoves: "F r' F' r U r U' r2 D' F r U' r F' D r" }
];


  const OLL_ALGS = OLL_BASE.map((alg) => ({
    ...alg,
    pattern: OLL_PATTERNS[alg.id] || PATTERNS.dot
  }));

  const PLL_ALGS = PLL_BASE.map((alg) => ({
    ...alg,
    pattern: PATTERNS.all
  }));

  const ALGORITHMS = [...OLL_ALGS, ...PLL_ALGS];

  window.CUBE_ALGS = ALGORITHMS;
  window.CUBE_OLL = OLL_ALGS;
  window.CUBE_PLL = PLL_ALGS;
})();
